In [8]:
import numpy as np
a = np.array([[1 , 2] , [5,6]])


In [2]:
a


array([[1, 2, 3],
       [5, 6, 7]])

In [3]:
b = np.array([[1 , 2, 3] , [5,6,7]])
a+b

array([[ 2,  4,  6],
       [10, 12, 14]])

In [4]:
a*b



array([[ 1,  4,  9],
       [25, 36, 49]])

In [9]:
np.dot(a, b)

array([[11, 14, 17],
       [35, 46, 57]])

In [11]:
print(np.sum( a , axis = 1))

[ 3 11]


In [12]:
a[0,1]


2

In [13]:
a[0]

array([1, 2])

In [14]:
a[0:]

array([[1, 2],
       [5, 6]])

In [15]:
a[0:1]

array([[1, 2]])

In [ ]:
a[]